Centralize All Data Pertaining to a Zillow House Listing in One Master File

# Date of Interest

In [1]:
date = '2024-07-09'

In [2]:
import os
import yaml
import datetime
import pandas as pd
import numpy as np

# Load the configuration file
with open(r'C:/Users/Dev/Documents/Real Estate Data/config/config.yaml', 'r') as file:
    config = yaml.safe_load(file)

# Directories

In [3]:
# Imported Data Directory
area_dir = config['data']['simplemaps_data']['master']
listing_dir = config['data']['zillow_data']['processed']['listings']['zillow_search_scraper']
census_dir = config['data']['census_data']['master']
tax_dir = config['data']['tax_data']['raw']
fred_dir = config['data']['fred_data']['master']

# Cleaned Data Directory
master_dir = config['data']['zillow_data']['master']['listings']['zillow_search_scraper']

# Files

In [4]:
# Imported Data 
area = 'zillow_area_categorization.csv'
listings = f'{date}_zillow_house_listings.csv'
census = 'census_master_data.csv'
tax = 'Texas County Tax Data.csv'
FRED = 'FRED_master_data.csv'

# Cleaned Data
master_file = f'{date}_zillow_listing_master.csv'

## Load Data Frame

In [5]:
file_path = os.path.join(area_dir, area)
area = pd.read_csv(file_path, low_memory=False)

file_path = os.path.join(listing_dir, listings)
listings = pd.read_csv(file_path, low_memory=False)

file_path = os.path.join(census_dir, census)
census = pd.read_csv(file_path, low_memory=False)

file_path = os.path.join(tax_dir, tax)
tax = pd.read_csv(file_path, low_memory=False)

In [6]:
#tax

## Filter Down Area Data frame

In [7]:
area = area[area['state'] == "Texas"]
area.drop('stateID', axis=1)

,state,metro,county,city,zipcode
616,Texas,Houston-The Woodlands-Sugar Land,Harris,Houston,77069.0
617,Texas,Houston-The Woodlands-Sugar Land,Harris,Houston,77068.0
618,Texas,Houston-The Woodlands-Sugar Land,Harris,Houston,77061.0
619,Texas,Houston-The Woodlands-Sugar Land,Harris,Houston,77060.0
620,Texas,Houston-The Woodlands-Sugar Land,Harris,Houston,77063.0
...,...,...,...,...,...
48172,Texas,NaN,Starr,Narciso Pena,78582.0
48175,Texas,NaN,La Salle,Fowlerton,78021.0
48180,Texas,Pittsburgh,Starr,Buena Vista,78582.0
48181,Texas,NaN,Dimmit,Brundage,78834.0
48189,Texas,NaN,Starr,Falcon Village,78545.0

Columns to add to listing: metro, county

Linking parameter: zipcode

# Add Area Data to listings dataframe

In [8]:
# Assuming both DataFrames have a 'zipcode' column to align on
listings = listings.merge(area[['zipcode', 'metro', 'county']], on='zipcode', how='left')
listings

,zipID,city,state,streetAddress,zipcode,latitude,longitude,beds,baths,homeType,...,builderName,newConstructionType,isPremierBuilder,is_newHome,flexFieldText,flexFieldType,url,webURL,metro,county
0,336813773,Crystal Beach,TX,109 Ocean Tide Dr,77650,29.421800,-94.697800,NaN,0.0,LOT,...,NaN,NaN,False,NaN,Showcase,showcase,https://www.zillow.com/homedetails/109-Ocean-T...,109-Ocean-Tide-Dr-Crystal-Beach-TX-77650/33681...,NaN,Galveston
1,27666682,Crystal Beach,TX,2598 Breaker Dr,77650,29.464958,-94.607540,4.0,4.0,SINGLE_FAMILY,...,NaN,NaN,False,NaN,1 day on Zillow,daysOnZillow,https://www.zillow.com/homedetails/2598-Breake...,2598-Breaker-Dr-Crystal-Beach-TX-77650/2766668...,NaN,Galveston
2,27689601,Pt Bolivar,TX,1415 Quarles Ave,77650,29.383598,-94.768166,3.0,2.0,SINGLE_FAMILY,...,NaN,NaN,False,NaN,4 days on Zillow,daysOnZillow,https://www.zillow.com/homedetails/1415-Quarle...,1415-Quarles-Ave-Pt-Bolivar-TX-77650/27689601_...,NaN,Galveston
3,89537714,Crystal Beach,TX,978 Biscayne,77650,29.471834,-94.596535,3.0,2.0,SINGLE_FAMILY,...,NaN,NaN,False,NaN,52 days on Zillow,daysOnZillow,https://www.zillow.com/homedetails/978-Biscayn...,978-Biscayne-Crystal-Beach-TX-77650/89537714_z...,NaN,Galveston
4,27686372,Crystal Beach,TX,2480 Gilmore,77650,29.461786,-94.610950,3.0,2.0,SINGLE_FAMILY,...,NaN,NaN,False,NaN,41 days on Zillow,daysOnZillow,https://www.zillow.com/homedetails/2480-Gilmor...,2480-Gilmore-Crystal-Beach-TX-77650/27686372_z...,NaN,Galveston
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32858,350280560,Humble,TX,16943 Chapel Knox Dr,77346,29.961803,-95.211220,3.0,2.0,SINGLE_FAMILY,...,Perry Homes,BUILDER_SPEC,True,True,NaN,NaN,https://www.zillow.com/homedetails/16943-Chape...,16943-Chapel-Knox-Dr-Humble-TX-77346/350280560...,Houston-The Woodlands-Sugar Land,Harris
32859,350280558,Humble,TX,16947 Chapel Knox Dr,77346,29.961803,-95.211220,4.0,3.0,SINGLE_FAMILY,...,Perry Homes,BUILDER_SPEC,True,True,NaN,NaN,https://www.zillow.com/homedetails/16947-Chape...,16947-Chapel-Knox-Dr-Humble-TX-77346/350280558...,Houston-The Woodlands-Sugar Land,Harris
32860,350280558,Humble,TX,16947 Chapel Knox Dr,77346,29.961803,-95.211220,4.0,3.0,SINGLE_FAMILY,...,Perry Homes,BUILDER_SPEC,True,True,NaN,NaN,https://www.zillow.com/homedetails/16947-Chape...,16947-Chapel-Knox-Dr-Humble-TX-77346/350280558...,Houston-The Woodlands-Sugar Land,Harris
32861,346206788,Humble,TX,"2330W Plan, The Groves 40'",77346,29.961805,-95.211220,3.0,3.0,SINGLE_FAMILY,...,PERRY HOMES,BUILDER_PLAN,True,True,NaN,NaN,https://www.zillow.com/community/groves-40/346...,"2330W-Plan,-The-Groves-40'-Humble-TX-77346/346...",Houston-The Woodlands-Sugar Land,Harris
32862,346206788,Humble,TX,"2330W Plan, The Groves 40'",77346,29.961805,-95.211220,3.0,3.0,SINGLE_FAMILY,...,PERRY HOMES,BUILDER_PLAN,True,True,NaN,NaN,https://www.zillow.com/community/groves-40/346...,"2330W-Plan,-The-Groves-40'-Humble-TX-77346/346...",Houston-The Woodlands-Sugar Land,Harris

# Add Tax Data to listings dataframe

In [9]:
# Assuming both DataFrames have a 'county' column to align on
listings = listings.merge(tax[['county', 'taxRate']], on='county', how='left')
#listings

## Property Specific Calculations

In [10]:
# Calculate Price per Square Foot
# Calculate Price per Square Foot and round to 2 decimal places
listings['pricePerSqft'] = (listings['price'] / listings['sqft']).round(2)

# Calculate Beds to Baths Ratio, round to 1 decimal place
listings['bedToBathRatio'] = (np.where(listings['baths'] != 0, (listings['beds'] / listings['baths']).round(1), np.nan)).round(1)
#listings

# Add Census Data to listings dataframe

In [11]:
# Assuming both DataFrames have a 'zipcode' column to align on
listings = listings.merge(census[['zipcode', 'medianIncome']], on='zipcode', how='left')
#listings

# Individual Monetary Estiamtions

### 20% Down Payment

In [12]:
# Assume a 20% Down Payment of Listing Price
listings['downPayment'] = (listings['price']*.20).round(0)

Monthly Housing Costs  - Should not exceed 30% of gross monthly income

### Mortgage

In [13]:
# Global Variables
interest = 6.95
r = ((interest/100)/12)
n = 30*12

# Calculate the mortgage for each listing
listings['mortgage'] = (listings['price'] * (r * (1 + r)**n) / ((1 + r)**n - 1)).round(0)

### Property Tax Estimation

In [14]:
listings['propertyTax'] = ((listings['taxAssessedValue']*listings['taxRate'])/12).round(0)

### Estimated Monthly Income

In [15]:
# Convert 'monthlyIncomeEstimate' to a numeric type
listings['medianIncome'] = pd.to_numeric(listings['medianIncome'])


listings['monthlyIncomeEstimate'] = ((listings['medianIncome']/12).round(0))

### Estimated Monthly Expenses

In [16]:
listings['insuranceEstimate'] = 150
listings['HOAEstimate'] = 300

listings['monthlyExpensesEstimate'] = listings['mortgage'] + listings['propertyTax'] + listings['insuranceEstimate'] + listings['HOAEstimate']

### Income to Expense Ratio

In [17]:
listings['I/E'] = (listings['monthlyIncomeEstimate'] / listings['monthlyExpensesEstimate']).round(2)

# Reoder columns

In [18]:
column_order = [
    # Location Information
    'zipID',
    'city',
    'state',
    'streetAddress',
    'zipcode',
    'latitude',
    'longitude',
    'metro',
    'county',

    # Property Details
    'homeType',
    'beds',
    'baths',
    'sqft',
    'acreage',
    'newConstructionType',
    'is_newHome',

    # Pricing Information
    'price',
    'priceChange',
    'zestimate',
    'rentZestimate',
    'taxAssessedValue',
    'pricePerSqft',
    'bedToBathRatio',

    # Listing Information
    'listingType',
    'daysOnZillow',
    'statusText',
    'statusType',
    'isFeaturedListing',
    'isShowcaseListing',
    'brokerName',
    'builderName',
    'isPremierBuilder',
    'flexFieldText',
    'flexFieldType',

    # Date Information
    'datePriceChanged',

    # Monetary Estimations
    'taxRate',
    'downPayment',
    
    # Income Information
    'medianIncome',
    'monthlyIncomeEstimate',

    # Monthly Expenses
    'monthlyExpensesEstimate',
    'I/E',
    'mortgage',
    'propertyTax',
    'insuranceEstimate',
    'HOAEstimate',
]

# Reorder the DataFrame columns
listings = listings[column_order]
listings

,zipID,city,state,streetAddress,zipcode,latitude,longitude,metro,county,homeType,...,taxRate,downPayment,medianIncome,monthlyIncomeEstimate,monthlyExpensesEstimate,I/E,mortgage,propertyTax,insuranceEstimate,HOAEstimate
0,336813773,Crystal Beach,TX,109 Ocean Tide Dr,77650,29.421800,-94.697800,NaN,Galveston,LOT,...,0.0055,53400.0,61211,5101.0,2284.0,2.23,1767.0,67.0,150,300
1,27666682,Crystal Beach,TX,2598 Breaker Dr,77650,29.464958,-94.607540,NaN,Galveston,SINGLE_FAMILY,...,0.0055,153800.0,61211,5101.0,5797.0,0.88,5090.0,257.0,150,300
2,27689601,Pt Bolivar,TX,1415 Quarles Ave,77650,29.383598,-94.768166,NaN,Galveston,SINGLE_FAMILY,...,0.0055,40000.0,61211,5101.0,1848.0,2.76,1324.0,74.0,150,300
3,89537714,Crystal Beach,TX,978 Biscayne,77650,29.471834,-94.596535,NaN,Galveston,SINGLE_FAMILY,...,0.0055,70000.0,61211,5101.0,2910.0,1.75,2317.0,143.0,150,300
4,27686372,Crystal Beach,TX,2480 Gilmore,77650,29.461786,-94.610950,NaN,Galveston,SINGLE_FAMILY,...,0.0055,155000.0,61211,5101.0,5828.0,0.88,5130.0,248.0,150,300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32858,350280560,Humble,TX,16943 Chapel Knox Dr,77346,29.961803,-95.211220,Houston-The Woodlands-Sugar Land,Harris,SINGLE_FAMILY,...,0.0064,69980.0,122321,10193.0,NaN,NaN,2316.0,NaN,150,300
32859,350280558,Humble,TX,16947 Chapel Knox Dr,77346,29.961803,-95.211220,Houston-The Woodlands-Sugar Land,Harris,SINGLE_FAMILY,...,0.0064,87980.0,122321,10193.0,NaN,NaN,2912.0,NaN,150,300
32860,350280558,Humble,TX,16947 Chapel Knox Dr,77346,29.961803,-95.211220,Houston-The Woodlands-Sugar Land,Harris,SINGLE_FAMILY,...,0.0064,87980.0,122321,10193.0,NaN,NaN,2912.0,NaN,150,300
32861,346206788,Humble,TX,"2330W Plan, The Groves 40'",77346,29.961805,-95.211220,Houston-The Woodlands-Sugar Land,Harris,SINGLE_FAMILY,...,0.0064,79380.0,122321,10193.0,NaN,NaN,2627.0,NaN,150,300
32862,346206788,Humble,TX,"2330W Plan, The Groves 40'",77346,29.961805,-95.211220,Houston-The Woodlands-Sugar Land,Harris,SINGLE_FAMILY,...,0.0064,79380.0,122321,10193.0,NaN,NaN,2627.0,NaN,150,300

# Save File

In [19]:
# Define the file path
csv_file_path = os.path.join(master_dir, master_file)
listings.to_csv(csv_file_path, index=False)